services:
    Mister6mik\SymfonyProfilerPlus\DataCollector\SymfonyProfilerPlusDataCollector:
        tags:
            - { name: data_collector, template: '@SymfonyProfilerPlus/Collector/symfony_profiler_plus.html.twig', id: 'symfony_profiler_plus' }
