services:
  Mister6mik\SymfonyProfilerPlus\DataCollector\SymfonyProfilerPlusDataCollector:
    tags: 
      - { name: data_collector, template: '@SymfonyProfilerPlus/collector.html.twig', id: 'symfony_profiler_plus' }